spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${HIBERNATE_SHOW_SQL:false}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/mpa_site}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:}

spring.datasource.initialization-mode=always
spring.datasource.continue-on-error=true

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
