spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/mpa_site
spring.datasource.username=postgres
spring.datasource.password=

spring.datasource.initialization-mode=always
spring.datasource.continue-on-error=true

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false


